### ISSUE TITLE
Please add Bill Of Materials

### ISSUE THREAD

**Issue by vuokko** [AlvaroRey/P3Steel_V4_20x30#1]
Could you add partlist to this project? Rods and bearings and their size etc.

**Comment by AlvaroRey** [comment]
Threaded Rods
2x Varilla roscada M5x295 mm

Smooth Rods
2x Ø8x375 mm X axis
2x Ø10x520 mm Y axis
2x Ø8x320 mm Z axis

Bearings
2 625zz bearings
1 624zz bearings
1 623zz bearings
2 Lm8luu bearing
3 Lm8uu bearing
3 SC10uu
2 coupling
2 Gt2 20 teeth pulleys
2 meters GT2 Belt

Electronics
Arduino Mega 2560  1 unit
RAMPS 1.4      1 unit
A4988 Driver   4 units
End Stops   3 units
Smart LCD   1 unit(Optional)
PSU 20A   1 unit (mininum)
Nema 17 70OZ   5 units

**Comment by MercadoNegro** [comment]
Regarding the bill of materials, my concern is if I have to print one of each plastic parts. If not, how many of each one?

**Comment by AlvaroRey** [comment]
In the name of each piece you got the numer of items you need to print
between parenthesis.

If you see no number in the piece, only print one.
